### ISSUE TITLE
Does it exist on Windows ?

### ISSUE THREAD

**Issue by Leosacha** [markusfisch/ScreenTime#18]
I use this app on my smartphone and thanks to it, I've reduce my daily screen time. Before, I was on my smartphone 4 hours per day. Nowadays, I'm only on it 1 hour per day. So first of all, thank you @markusfisch to save my time, by just notify me, and display, how much time I've spent.

My request is considering now Windows. Anybody knows is there is an equal app that just notify on taskbar the daily screen time on Windows ?

**Comment by markusfisch** [comment]
That's great! Happy to hear that! 😄 

Unfortunately I don't know of a similar software for Windows. But I'm sure there must be something! Googling for "windows screen time recorder" gives quite some results 😉 Maybe there's something for you? (I don't use Windows so I can't tell 😬)

**Comment by Leosacha** [comment]
Alright, thank you for your help !
I've contacting the developer of a windows screentime app on Github. He will update soon his app to display daily screentime in the taskbar.
Here it is : https://github.com/Levminer/screentime
