### ISSUE TITLE
Autostart

### ISSUE THREAD

**Issue by RedFish87** [markusfisch/ScreenTime#32]
Pls is there a way to start the app every time I turn on my Android?

**Comment by markusfisch** [comment]
It already should do so. You may have to give it some time, but it should come up eventually.

**Comment by RedFish87** [comment]
It already works! I had to tap the battery icon and cancel the battery
saver regime. Thanks)

Dne ne 14. 7. 2024 11:57 uživatel Markus Fisch ***@***.***>
napsal:

**Comment by Vihershunde** [comment]
Thank you @RedFish87 @markusfisch
