### ISSUE TITLE
Adjustable cutoff time for a 24h period?

### ISSUE THREAD

**Issue by Anonymous1157** [markusfisch/ScreenTime#5]
Hi! This app is surprisingly useful for being so simple. Unfortunately I work nights, and changing the day at midnight doesn't make any sense for displaying my screen time habits when I am only looking at two or three days of history in the chart. I would like to be able to define some arbitrary time in the middle of sleeping to change the day.

**Comment by markusfisch** [comment]
I understand completely! And I've even played with the idea, but wasn't sure how many people would find it useful. So that answers the question 😉 

Expect this feature with the next update.

**Comment by markusfisch** [comment]
Added in version 1.1.0 which is now available.
